import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Body from "./body";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="flex flex-col h-screen">
      <Body className={inter.className}>{children}</Body>
    </html>
  );
}
